# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainbowlive_gif', '0002_auto_20171129_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_ja',
            field=models.CharField(default='', max_length=100),
        ),
    ]
