# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainbowlive_gif', '0003_tag_name_ja'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='is_updated_to_giphy',
            field=models.BooleanField(default=False),
        ),
    ]
