# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-18 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainbowlive_gif', '0004_gif_updated_to_giphy'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='tweet_url',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
