# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-29 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gif',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='gif',
            name='filename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
